# File paths
- data:
    rawFilePath: data/raw/
    clnFilePath: data/processed/
    intFilePath: data/interim/
    outPath: reports/figures/
    downloadPaths:
        cjs_dec_2024: https://www.gov.uk/api/content/government/statistics/criminal-justice-system-statistics-quarterly-december-2024
    datasetFilenames:
        outcomes_by_offence: sentence_outcomes_2017_2024.csv
        outcomes_by_offence_earlier: sentence_outcomes_2010_2016.csv
        filter_sentence_type: women_cust_comm_sus.csv
        group_pfa_sentence_outcome: women_cust_comm_sus_FINAL.csv
        filter_sentence_length: women_cust_sentence_len_FINAL.csv
        make_custody_tables_template: PFA_custodial_sentences_{category}_FINAL.csv
        filter_custody_offences: PFA_custodial_sentences_by_offence_{year}_FINAL.csv
        ons_cleaning: LA_population_women_{min_year}-{max_year}.csv

- outcomes_by_offence_filter:
    include:
        sex:
            - Female
        outcome:
            - Immediate Custody
            - Community Sentence
            - Suspended Sentence
        age_group:
            - Adults
            - Young adults
    exclude:
        pfa:
            - Not known
    sort_by:
        - year
        - pfa

- viz:
    filePaths:
        custody_sentence_lengths: custody_sentence_lengths
        sentence_types: sentence_types
        custody_offences: custody_offences
    