channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - nbqa
  - jupyterlab
  - notebook
  - python-kaleido
  - python-dotenv
  - seaborn
  - plotly
  - ipywidgets
  - cookiecutter
  - pandas
  - plotly::plotly-geo
  - chart-studio
  - python
  - black
  - poppler