site_name: Imprisonment of women
site_description: An analysis of sentencing outcomes for women by police force area in England and Wales 
repo_url: https://github.com/Prison-Reform-Trust/womens-imprisonment-PFA
edit_uri: edit/master/docs/
copyright: Written by Prison Reform Trust
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - navigation.instant
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: prison-reform-trust
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  icon:
    admonition:
      tip: material/tooltip-check-outline
extra_css:
  - css/extra.css
nav:
  - Welcome: index.md
  - Getting started:
    - getting-started/index.md
    - Downloading the data: getting-started/downloading-the-data.md
    - Processing the data: getting-started/processing-the-data.md
  - Quality assurance:
    - Criminal Justice Statistics: quality-assurance/CJS_PFA.md
    - ONS population estimates: quality-assurance/ONS-population.md
    - Matching populations to PFAs: quality-assurance/population-to-pfa.md